### ISSUE TITLE
Just a clarification about the dropout.

### ISSUE THREAD

**Issue by itsmohitanand** [kratzert/ealstm_regional_modeling#2]
The dropout rate by default is set to 0. So is it right to assume that no dropout was used? And any experience on how did the dropout affect the training, if it was done during the testing phase will be helpful.

**Comment by kratzert** [comment]
The dropout rate is set to zero per default, because when creating the dropout layer you have to pass a value. In case that the user forgets to set one, the codebase will fallback to this default.
However for our runs, as also indicated in the paper, we used a dropout rate of 0.4. See the definitions of the global settings here: https://github.com/kratzert/ealstm_regional_modeling/blob/d11815824793737f28f125d55477e42f8900a78e/main.py#L43

**Comment by itsmohitanand** [comment]
> The dropout rate is set to zero per default, because when creating the dropout layer you have to pass a value. In case that the user forgets to set one, the codebase will fallback to this default.
> However for our runs, as also indicated in the paper, we used a dropout rate of 0.4. See the definitions of the global settings here:
> 
> https://github.com/kratzert/ealstm_regional_modeling/blob/d11815824793737f28f125d55477e42f8900a78e/main.py#L43

Thank you for your prompt reply.
